# Generated by Django 4.1 on 2022-12-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=30)),
                ("position", models.CharField(max_length=30)),
                ("salary", models.IntegerField()),
            ],
        ),
    ]
